server:
  port: 8081

spring:
  application:
    name: auth-service

  # Redis Configuration for token storage
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
          enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

# JWT Configuration
jwt:
  secret: "dGhpc2lzYXZlcnlzZWN1cmVzZWNyZXRrZXlmb3JsaWdodG5vdmVscGxhdGZvcm0yMDI1"
  access-token:
    expiration: 86400000  # 24 hours in milliseconds
  refresh-token:
    expiration: 604800000 # 7 days in milliseconds
  issuer: "light-novel-platform"

# User Service Configuration
user-service:
  url: http://localhost:8000
  endpoints:
    get-user-by-email: "/api/v1/users/email/{email}"
    get-user-by-id: "/api/v1/users/{id}"
    update-last-login: "/api/v1/users/{id}/last-login"

# Security Configuration
security:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:3001,https://lightnovel.com"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    exposed-headers: "Authorization"
    allow-credentials: true
    max-age: 3600

# Rate Limiting
rate-limit:
  login:
    requests: 5
    window: 900 # 15 minutes
  refresh:
    requests: 10
    window: 3600 # 1 hour

# Logging Configuration
logging:
  level:
    com.lqviet.authservice: DEBUG
    org.springframework.security: DEBUG
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/auth-service.log

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: true

# Feign Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  httpclient:
    enabled: true