services:
  account-service-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=noveldb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    networks:
      - internal
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis for Auth Service
  auth-service-redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'
    networks:
      - internal
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  account-service:
#    image: 'lqviet455/account-service:latest'
    container_name: account-service
    build:
      context: ./account-services
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://account-service-postgres:5432/noveldb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    ports:
      - '8000:8000'
    depends_on:
      - user-service-postgres
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
  redisdata: