services:
  user-service-postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=noveldb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432'
