package com.lqviet.accountservices.enums;

public enum ActivityType {
    LOGIN, LOGOUT, PASSWORD_CHANGE, EMAIL_CHANGE, PROFILE_UPDATE,
    ADDRESS_ADD, ADDRESS_UPDATE, ADDRESS_DELETE,
    SETTING_CHANGE, ACCOUNT_DEACTIVATE, ACCOUNT_REACTIVATE,
    FAILED_LOGIN, ACCOUNT_LOCKED, ACCOUNT_UNLOCKED,
    PASSWORD_RESET_REQUEST, PASSWORD_RESET_COMPLETE,
    EMAIL_VERIFICATION, PHONE_VERIFICATION
}
